jobs:
  - name: dataworks-kafka-reconciliation-infrastructure-pr
    plan:
      - get: dataworks-kafka-reconciliation-infrastructure-pr
        trigger: true
        version: every
      - get: dataworks-aws-glue-launcher-release
      - get: dataworks-athena-reconciliation-launcher-release
      - put: dataworks-kafka-reconciliation-infrastructure-pr
        params:
          path: dataworks-kafka-reconciliation-infrastructure-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-kafka-reconciliation-infrastructure: dataworks-kafka-reconciliation-infrastructure-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-kafka-reconciliation-infrastructure: dataworks-kafka-reconciliation-infrastructure-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: dataworks-kafka-reconciliation-infrastructure-pr
          params:
            path: dataworks-kafka-reconciliation-infrastructure-pr
            status: failure
        on_success:
          put: dataworks-kafka-reconciliation-infrastructure-pr
          params:
            path: dataworks-kafka-reconciliation-infrastructure-pr
            status: success
