jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: dataworks-kafka-reconciliation-infrastructure
        passed:
          - qa
        trigger: true
      - get: dataworks-aws-glue-launcher-release
        passed:
          - qa
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'
