jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: dataworks-kafka-reconciliation-infrastructure
        passed:
          - qa
        trigger: true
      - get: dataworks-aws-glue-launcher-release
        version: { tag: ((glue-launcher-version.preprod)) }
        passed:
          - qa
        trigger: true
      - get: dataworks-athena-reconciliation-launcher-release
        version: { tag: ((athena-reconciliation-version.preprod)) }
        passed:
          - qa
        trigger: true
      - get: dw-al2-ecs-ami
        passed:
          - qa
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'preprod'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'preprod'
