jobs:
  - name: production
    max_in_flight: 1
    plan:
      - get: dataworks-kafka-reconciliation-infrastructure
        passed:
          - preprod
        trigger: true
      - get: dataworks-aws-glue-launcher-release
        version: { tag: ((glue-launcher-version.production)) }
        passed:
          - preprod
        trigger: true
      - get: dataworks-athena-reconciliation-launcher-release
        version: { tag: ((athena-reconciliation-version.production)) }
        passed:
          - preprod
        trigger: true
      - get: dw-al2-ecs-ami
        passed:
          - preprod
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'production'
