jobs:
  - name: production
    max_in_flight: 1
    plan:
      - get: dataworks-kafka-reconciliation-infrastructure
        passed:
          - preprod
        trigger: true
      - get: dataworks-aws-glue-launcher-release
        passed:
          - preprod
        trigger: true
      - get: dataworks-athena-reconciliation-launcher-release
        passed:
          - preprod
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'production'
