jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - get: dataworks-kafka-reconciliation-infrastructure
        trigger: true
      - get: dataworks-aws-glue-launcher-release
        trigger: true
      - get: dataworks-athena-reconciliation-launcher-release
        trigger: true

      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'
